//! # DBus interface proxy for: `net.boothwhack.BingDaily1`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `Interface '/net/boothwhack/BingDaily1' from service 'net.boothwhack.BingDaily1' on session bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!
//! This DBus object implements
//! [standard DBus interfaces](https://dbus.freedesktop.org/doc/dbus-specification.html),
//! (`org.freedesktop.DBus.*`) for which the following zbus proxies can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! …consequently `zbus-xmlgen` did not generate code for the above interfaces.

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "net.boothwhack.BingDaily1",
    default_service = "net.boothwhack.BingDaily1",
    default_path = "/net/boothwhack/BingDaily1"
)]
trait BingDaily1 {
    /// CurrentPicture property
    #[dbus_proxy(property)]
    fn current_picture(&self) -> zbus::Result<String>;
}
